# Generated by Django 4.2.29 on 2026-03-06 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.IntegerField(default=2000)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('sabah', '🌅 Sabah Kahvaltısı'), ('ogle', '☀️ Öğle Yemeği'), ('aksam', '🌙 Akşam Yemeği'), ('ara', '🍎 Ara Öğün')], default='ogle', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_description', models.TextField(help_text='Yemek açıklaması')),
                ('total_calories', models.IntegerField(default=0)),
                ('protein_g', models.FloatField(default=0, verbose_name='Protein (g)')),
                ('carbs_g', models.FloatField(default=0, verbose_name='Karbonhidrat (g)')),
                ('fat_g', models.FloatField(default=0, verbose_name='Yağ (g)')),
                ('ai_analysis', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
