# Generated by Django 5.1.4 on 2026-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile_target_weight_kg_weightlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_description',
            field=models.TextField(blank=True, help_text='Yemek açıklaması'),
        ),
    ]
