# Generated by Django 5.2.12 on 2026-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_meal_food_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_fit_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_fit_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
