# Generated by Django 5.2.12 on 2026-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_userprofile_google_fit_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="burned_calories_manual",
            field=models.IntegerField(default=0),
        ),
    ]
