# Generated by Django 6.0.3 on 2026-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_exercise_workoutlog_setlog_workoutprogram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutprogram',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='day',
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
