# Generated by Django 4.2.16 on 2026-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_workoutprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, default='orta', max_length=20, verbose_name='Aktivite Seviyesi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kadin', 'Kadın')], default='erkek', max_length=10, verbose_name='Cinsiyet'),
        ),
    ]
